config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/team', to: 'contact#team' #page de la team
  get '/contact', to: 'contact#contact' #page pour le contact
  get 'welcome/:first_name', to: 'welcome#user' #si le nom est renseigné
  get 'welcome', to: 'welcome#user' #si le nom n'est pas renseigné
  root to: 'gossip_page#index' #page d'accueil
  get 'gossip/:id', to: 'gossip_page#show' #page du gossip
  get 'author/:id', to: 'gossip_page#author' #page de l'auteur
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users 	#City en relation 1-N avec User
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user		#Comment en relation N-1 avec user et gossip et en relation N-1 avec Like 
	belongs_to :gossip
	has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	has_many :tag_lists 		#Gossip en relation N-1 avec User et en relation 1-N avec Comment et Like, et en relation N-N avec Tags
	has_many :tags, through: :tag_lists
	belongs_to :user
	has_many :comments
	has_many :likes

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user		#Like est en relation N-1 avec User, comment et Gossip et dont ces 2 derniers sont optionnels
	belongs_to :comment, optional: true
	belongs_to :gossip, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"      #PrivateMessage est en relation 1-N avec User en utilisant une classe_name et en relation N-N avec User pour les recipient
	has_many :recipients
	has_many :users, through: :recipients
end

app/models/recipient.rb
class Recipient < ApplicationRecord
	belongs_to :private_message   #Recipient fait la liaison N-N entre privatemessage et user pour les receveurs
	belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tag_lists		#Tag a une relation N-N avec Gossip
	has_many :gossips, through: :tag_lists
end

app/models/tag_list.rb
class TagList < ApplicationRecord
	belongs_to :gossip	#TagList fait la relatin N-N entre Tag et Gossip
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city		#User est en relation N-1 avec City, en relation 1-N avec Like, comment ,gossip et privatemessage et en relation N-N avec private message
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :recipients
	has_many :private_messages, through: :recipients
	has_many :comments
	has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def contact
  end

  def team
  end

end

app/controllers/gossip_page_controller.rb
class GossipPageController < ApplicationController

  def index
    @gossips = Gossip.all
  end

  def show
    id_gossip = params[:id].to_i
    @gossip = Gossip.all[id_gossip]
  end

  def author
    id_author = params[:id].to_i
    @user = User.all[id_author]
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def user
    @first_name = params[:first_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_page_helper.rb
module GossipPageHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/contact.html.erb
<br>
<h1>Contact</h1>
<br>
<div class="card">
  <div class="card-body">
    <p>Pour prendre contact avec l'équipe : </p>
    <p>Rendez-vous sur le slack !</p>
  </div>
</div>

app/views/contact/team.html.erb
<br>
<h1>Team</h1>
<br>
<div class="card">
  <div class="card-body">
    <p>Voici mon équipe lol mdr 😇❤️😻 </p>
    <p>Une équipe composée de moi-même, jenny en remote </p>
  </div>
</div>

app/views/gossip_page/author.html.erb
<br>
<div class="container" style="text-align: center;">
<div class="card border-success text-center mb-3" style="max-width: 18rem;">
  <div class="card-header">L'auteur : <%= "#{@user.first_name} #{@user.last_name}, #{@user.age} ans, se trouvant à #{@user.city.name}" %>  </div>
  <div class="card-body text-success">
    <h5 class="card-title">Sa description : <%= @user.description %> </h5>
    <p class="card-text">Pour lui envoyer un email : <a href="mailto:#{<%= @user.email %>}"> <%= @user.email %> </a></p>
  </div>
</div>

app/views/gossip_page/index.html.erb
<br>
<h1>Bienvenue sur mon super site de potins !</h1>
<br>
<div class="container">
<% @gossips.each do |gossip| %><br>
<div class="row">
  <div class="col-sm-6">
    <div class="card text-center">
      <div class="card-body">
        <h5 class="card-title"><%= gossip.title %></h5>
        <p class="card-text"><%= gossip.user.first_name %></p>
        <a href="/gossip/<%= gossip.id %>" class="btn btn-success">Savoir ce que raconte ce potin</a>
      </div>
    </div>
  </div>
</div>
<% end %>  
</div>

app/views/gossip_page/show.html.erb
<br>
<div class="card">
  <div class="card-header">
    <h1><%= @gossip.title %></h1>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @gossip.content %></p>
      <footer class="blockquote-footer">Date de création <cite title="Source Creation"><%= @gossip.created_at %></cite></footer>
    </blockquote>
  </div>
</div>
<br>
<br>
<a class="btn btn-success" href="/author/<%= @gossip.user_id %>">Plus de détails sur l'auteur</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- CDN bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Accueil", root_path, class: "nav-link" %>
            <span class="sr-only">(current)</span>
          </li>
          <li class="nav-item">
            <%= link_to "Team", team_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

   
    <div class="container">
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/welcome/user.html.erb
<br>
<h1>Bienvenue sur notre super site de potins <%= @first_name %> !</h1>
<br>
<div class="card">
  <div class="card-body">
    <p>Il est pas ouf encore mais ca va venir </p>
  </div>
</div>